# Generated by Django 5.0.3 on 2024-04-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
